import json
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List
from core.event_engine import EventEngine

class TimelineEngine:
    def __init__(self, event_engine: EventEngine):
        self.event_engine = event_engine

    def generate_timeline(self, person_id: str) -> Dict[str, Any]:
        """
        Queries database events to build a chronological sighting timeline.
        
        Args:
            person_id (str): The ID of the target person.
            
        Returns:
            Dict[str, Any]: Structured timeline data.
        """
        person = self.event_engine.get_person(person_id)
        person_name = person["name"] if person else "Unknown Person"
        person_category = person["category"] if person else "Watchlist"
        
        events = self.event_engine.get_events_for_person(person_id)
        
        sightings = []
        for evt in events:
            # Query camera location dynamically
            camera_loc = "Unknown Location"
            try:
                with self.event_engine._get_connection() as conn:
                    cursor = conn.execute("SELECT location FROM cameras WHERE camera_id = ?", (evt["camera_id"],))
                    row = cursor.fetchone()
                    if row:
                        camera_loc = row["location"]
            except Exception:
                pass

            sightings.append({
                "event_id": evt["event_id"],
                "camera_id": evt["camera_id"],
                "camera_location": camera_loc,
                "video_source": evt["video_source"],
                "timestamp": evt["timestamp"],
                "frame_number": evt["frame_number"],
                "confidence": evt["confidence"],
                "bounding_box": evt["bounding_box"],
                "match_details": evt["match_details"]
            })
            
        # Summary statistics
        total_sightings = len(sightings)
        cameras_seen = list(set([s["camera_id"] for s in sightings]))
        
        timeline = {
            "person_id": person_id,
            "person_name": person_name,
            "category": person_category,
            "total_sightings": total_sightings,
            "cameras_visited_count": len(cameras_seen),
            "cameras_visited": cameras_seen,
            "sightings": sightings
        }
        
        return timeline

    def save_timeline_report(self, timeline: Dict[str, Any], output_json_path: Path, output_md_path: Path):
        """
        Saves the timeline as a structured JSON file and a readable Markdown report.
        """
        # 1. Save JSON
        output_json_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_json_path, "w") as f:
            json.dump(timeline, f, indent=4)
        print(f"[INFO] Timeline JSON saved to {output_json_path}")
        
        # 2. Save Markdown
        output_md_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_md_path, "w") as f:
            f.write(f"# VisionGuard Sighting Sighting Timeline Report\n\n")
            f.write(f"## Target Information\n")
            f.write(f"- **Person ID:** {timeline['person_id']}\n")
            f.write(f"- **Name:** {timeline['person_name']}\n")
            f.write(f"- **Category:** {timeline['category']}\n")
            f.write(f"- **Total Sightings:** {timeline['total_sightings']}\n")
            f.write(f"- **Unique Cameras Visited:** {timeline['cameras_visited_count']} ({', '.join(timeline['cameras_visited'])})\n\n")
            
            f.write(f"## Chronological Sighting Log\n\n")
            if not timeline["sightings"]:
                f.write("*No sightings logged for this person.*\n")
            else:
                f.write("| No. | Timestamp | Camera ID | Location | Video Source | Confidence | Bounding Box |\n")
                f.write("|---|---|---|---|---|---|---|\n")
                for idx, s in enumerate(timeline["sightings"], 1):
                    bbox_str = f"[{s['bounding_box'][0]}, {s['bounding_box'][1]}, {s['bounding_box'][2]}, {s['bounding_box'][3]}]"
                    f.write(f"| {idx} | `{s['timestamp']}` | **{s['camera_id']}** | {s['camera_location']} | `{s['video_source']}` | {s['confidence']:.2f} | `{bbox_str}` |\n")
                    
            f.write(f"\n\n*Generated by VisionGuard Surveillance Intelligence Platform on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*\n")
        print(f"[INFO] Timeline Markdown report saved to {output_md_path}")
